# Generated by Django 4.0.5 on 2022-07-02 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtext', models.CharField(max_length=200)),
                ('choices', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=2)),
                ('adding_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.CharField(max_length=10)),
                ('quiz_count', models.IntegerField()),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('questions_count', models.IntegerField()),
                ('question', models.ManyToManyField(related_name='category', to='quizzes.question')),
                ('quiz', models.ManyToManyField(related_name='category', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
