# Generated by Django 4.0.5 on 2022-07-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='questions_count',
            new_name='quiz_count',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_count',
            new_name='question_count',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_number',
            new_name='quiz_name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='create_date',
        ),
    ]
