# Generated by Django 4.0.5 on 2022-07-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_questions_count_category_quiz_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_name',
            new_name='quiz_category',
        ),
    ]
