# Generated by Django 4.0.5 on 2022-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_remove_category_questions_category_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
